### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by atukilham** [michalsn/CodeIgniter-PJAX#1]
How to use this?

**Comment by michalsn** [comment]
1. Read up about [jquery-pjax](https://github.com/defunkt/jquery-pjax)
2. Install hook from this repo by following the instructions from readme

**Comment by atukilham** [comment]
Thanks for reply.
I was tried and follow instructions, including instruction from jquery pjax, but my page not load like ajax pages. It's still like normal page when click a link. I was confused how to call view in controller.
Can you give an example?

Thanks

**Comment by michalsn** [comment]
https://github.com/michalsn/CodeIgniter-PJAX-example

**Comment by atukilham** [comment]
Thank you so much @michalsn
